#!/bin/bash

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -f|--force)
    CACHE="--no-cache"
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters


show_usage() {
    echo -e "Usage: $0 [-f|--force] branch_name"
    echo -e "    -f|--force deactivate the cache"
}

if [ "$#" -ne 1 ]; then
    show_usage
    exit 1
fi

git checkout $1 && \
docker build $CACHE -t fredtingaud/quick-bench:$1 . && \
(cd ../quick-bench-back-end; QB_VERSION=$1 mocha system-test --exit) && \
echo "pushing $1" && \
docker push fredtingaud/quick-bench:$1 && \
git checkout master
