#!/bin/bash

fmt='./tmp-build-one %(refname:short)' 

cp build-one tmp-build-one
git for-each-ref --shell --format="$fmt" refs/heads/gcc* | while read entry; do eval "$entry"; done
git for-each-ref --shell --format="$fmt" refs/heads/clang* | while read entry; do eval "$entry"; done
rm tmp-build-one
