#! /bin/bash

stty cols 200

echo "[version]"
echo "1"

echo "[std]"
gcc --help -v 2>/dev/null | grep "^  \-std=c++" | grep -v Deprecated | grep -v "c++98" | grep -v "c++03" | grep -v "Same as" | grep -v "Deprecated" | grep -Eo 'c\+\+[0-9a-z]+'
