#!/bin/bash
set -e

FILENAME=$1
PREPROC=$2
ASM=$3
PARAMETERS="${@:4}"

if [ $PREPROC = true ]; then
    g++ -E $PARAMETERS $FILENAME > bench.i
fi

if [ "$ASM" != "none" ]; then
    g++ -S -masm=$ASM -o bench.ss $PARAMETERS $FILENAME
    # -S tries to remove the output instead of overwriting it.
    # That is a problem when trying to get the file out of docker through a shared file
    # So instead we use a temp file then cp on the target, that will overwrite
    cp bench.ss bench.s
fi
