#!/bin/bash
set -e

FILENAME=$1
PARAMETERS="${@:2}"
COUNTER=0
SECONDS=0
# default 60s timeout can be changed with an environment variable
MAX_TIME="${BB_TIMEOUT:-60}"
MAX_COUNTER="${BB_MAX:-20}"
LAST_TIME=0
LAST_DURATION=0

while [[ $COUNTER -lt $MAX_COUNTER && $SECONDS -lt $((MAX_TIME - LAST_DURATION)) ]]; do
  script --flush --quiet --return output.txt --command "/usr/bin/time -o one-bench.out -f \"%U\t%M\" clang++ $PARAMETERS $FILENAME"
  let COUNTER=COUNTER+1
  (let LAST_DURATION=SECONDS-LAST_TIME) || true
  cat one-bench.out >> bench.out
  (let LAST_TIME=SECONDS) || true
done
